remote_theme: mmistakes/so-simple-theme
title: Hub Ambiental Brasil
description: Portal independente de notícias sobre sustentabilidade e economia circular
url: "https://ambisocial.github.io"
baseurl: "/hub-ambiental-brasil"
author: Redação Hub Ambiental Brasil
email: contato@hub-ambiental-brasil.com
lang: pt-BR
timezone: America/Sao_Paulo
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
paginate: 10
paginate_path: "/page:num/"
